### PR TITLE
Testing/1.0.2

### PR DESCRIPTION
**Pull request by feliwir**

### CODE REVIEW

**Review by Croydon — COMMENTED** [review]
Are all of the patches now applied upstream or not needed anymore? Please explain your changes better

**Comment by feliwir** [comment]
Applying the patch didn’t work anymore. I still need to check what the upstream CMakeLists.txt looks how. Just did the PR to trigger the CI

**Comment by uilianries** [comment]
> Applying the patch didn’t work anymore.

What do you mean, what error do you have?

Excluding our CMake won't work, because libwebp doesn't export its symbols on Windows.

**Comment by SSE4** [comment]
@feliwir this is green now. actions needed:
1. convert `replace_in_file` into patches and use `tools.patch` in the recipe
2. submit patches upstream

**Comment by SSE4** [comment]
something has to be fixed in MSVC builds, seems like symbols aren't exported...

**Comment by uilianries** [comment]
the patch 01 is wrong. give me some minutes I'll provide a new patch

**Comment by uilianries** [comment]
@feliwir thanks for your contribution. I just fixed your dll patch. Let's wait for CI result to promote it on stable branch.

**Pull request merged**
