### PR TITLE
Define Android specific cmake variables ANDROID_ABI/ANDROID_NDK

### PR DESCRIPTION
**Pull request by CAMOBAP**
Without this variables, cmake configuration process failed

So till https://github.com/conan-io/conan/issues/3099 will approved/implemented, I kindly ask you to review/approve this PR

### CODE REVIEW

**Comment by SSE4** [comment]
@CAMOBAP795 is it required only for webp, or for each package?
/cc @theodelrieu

**Comment by CAMOBAP** [comment]
@SSE4 webp is 'private case', but usually to cross-compile something to Android https://android.googlesource.com/platform/ndk/+/master/build/cmake/android.toolchain.cmake (or similar) used and it expect to have ANDROID_NDK & ANDROID_ABI

**Comment by SSE4** [comment]
I am merging it for now, but it doesn't scale well to add this definitions to each recipe, it's much better to open PR against conan to define these two for Android automatically

**Comment by theodelrieu** [comment]
I agree this is not scalable, we need a recommended/standard way to pass flags like that.

I would (unsurprisingly) recommend using my [android-ndk](https://github.com/theodelrieu/conan-android-ndk) recipe instead :)

**Comment by CAMOBAP** [comment]
@theodelrieu I agree with your point and thanks for great job done with https://github.com/theodelrieu/conan-android-ndk 

Unfortunately it will not fit my needs because I need to use already installed NDK

**Comment by theodelrieu** [comment]
>Unfortunately it will not fit my needs because I need to use already installed NDK

Interesting, that could be a good improvement to the recipe (i.e. supporting already installed NDKs)

**Pull request merged**
