### PR TITLE
Don't set ANDROID_ABI if CMAKE_ANDROID_ARCH_ABI not set

### PR DESCRIPTION
**Pull request by CAMOBAP**
I have faced with issue that when used `CONAN_CMAKE_TOOLCHAIN_FILE` approach

### CODE REVIEW

**Comment by SSE4** [comment]
@CAMOBAP795  what was the error message?

**Comment by CAMOBAP** [comment]
@SSE4 

```
ERROR: libwebp/1.0.0@bincrafters/stable: Error in build() method, line 106
        cmake = self._configure_cmake()
while calling '_configure_cmake', line 69
        cmake.definitions['ANDROID_ABI'] = cmake.definitions['CMAKE_ANDROID_ARCH_ABI']
        KeyError: 'CMAKE_ANDROID_ARCH_ABI'
```

**Comment by SSE4** [comment]
ah, yep, it definitely makes sense. thanks for the clarification, I was thinking it was set by conan, but it seems like it might be set by toolchain, or might not be.

**Comment by CAMOBAP** [comment]
Once https://github.com/conan-io/conan/pull/4538 will be ready, I hope we will have less such workarounds

**Pull request merged**
